global_costmap:
  global_frame: map
  #robot_base_frame: lidar_1_link
  robot_base_frame: mpo_700_base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
#  transform_tolerance: 2

  static_map: true
  clearing: true
